services:
  postgresql-local-speech:
    image: 'postgres:alpine'
    container_name: postgresql-local-speech
    ports:
      - "5401:5432"
    environment:
      - POSTGRES_DB=speech
      - POSTGRES_USER=speech
      - POSTGRES_PASSWORD=123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
